package:
  name: robustraster
  version: "0.4.0"

source:
  path: .

build:
  noarch: python
  number: 1
  script: python -m pip install ./src

requirements:
  build:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy >=2.0
    - xee =0.0.13
    - rioxarray =0.15.0
    - dask =2024.8.1
    - distributed =2024.8.1
    - cloudpickle =3.0.0
    - lz4 =4.3.3
    - msgpack-python =1.0.8
    - pandas =2.2.2
    - tornado =6.4.2
    - geopandas =1.0.1
    - gcsfs =2025.3.2
    - gdal =3.10.2
    - ipykernel =6.29.5

test:
  source_files:
    - tests/
  requires:
    - pytest
    - gdal
  commands:
    - pytest tests/

extra:
  recipe-maintainers:
    - adrianom

about:
  summary: "run() function + hooks"
  license: "MIT"
  description: |
    Version 0.4.0 adds a new run() function, meant to be the interface for users to access the functionality of robustraster without having to deal with OOP. Also, added ways to run preprocessing/postprocessing functions via hooks.