name: robust_raster
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - xee=0.0.13
  - rioxarray=0.15.0
  - dask=2024.8.1
  - distributed=2024.8.1
  - cloudpickle=3.0.0
  - lz4=4.3.3
  - msgpack-python=1.0.8
  - numpy=2.0.1
  - pandas=2.2.2
  - tornado=6.4.1
  - pip:
      - earthengine-api  # Include any additional packages you need that are installed via pip
      - docker
