from dask.distributed import Client, LocalCluster
import xarray as xr
import multiprocessing
import psutil

class DaskHandler:
    def __init__(self, dask_client: Client = None) -> None:
        '''
        Initialize the DaskHandler class. Creates a dask_client attribute that will
        be used to store the Dask Client information.
        '''
        self.dask_client = dask_client

    def _bytes_to_gigabytes(self, memory: int) -> int:
        '''
        Private method that takes the system memory in bytes and converts it to gigabytes.

        Parameters:
        - memory (int): The total system memory of the machine in bytes. 

        Returns:
        - int: The system memory converted to gigabytes
        '''

        gigabytes = memory / (1024 ** 3)
        return gigabytes
    
    def create_local_threads(self) -> None:
        '''
        Store dask_client attribute with a Dask Client object configured to use the local threads
        on the machine.
        '''
        self.dask_client = Client(processes=False)

    def create_local_cluster(self) -> None:
        '''
        Store dask_client attribute with a Dask Client object configured to generate a LocalCluster object. LocalCluster 
        configuration is autogenerated by take the number of CPU cores in the given maachine, creating one worker
        per core (with each worker getting one thread), and allocating memory to each worker based on the system 
        memory divided by the number of cores (or number of workers). 
        '''
        num_cores = multiprocessing.cpu_count()
        total_memory = psutil.virtual_memory().total
        total_memory_gb = self._bytes_to_gigabytes(total_memory)
        memory_per_worker = f"{int(total_memory_gb / num_cores)}GB"
        self.dask_client = Client(LocalCluster(n_workers=num_cores, threads_per_worker=1, memory_limit=memory_per_worker))

    def connect_to_cloud_cluster(self, scheduler_address: str):
        '''
         Store dask_client attribute with a Dask Client object configured (WIP) to connect to a Cloud service.
        '''
        self.dask_client = Client(scheduler_address)

    def process_with_dask(self, dataset: xr.Dataset) -> xr.Dataset:
        '''
        If the dask_client attribute is not None, then chunk the dataset to convert it to a Dask array.

        Parameters:
        - dataset (xr.Dataset): An xarray Dataset object that will be chunked.

        Returns:
        - xr.Dataset: An xarray dataset object now configured to be a Dask array.
        '''
        if self.dask_client:
            return dataset.chunk({'time': -1, 'latitude': 256, 'longitude': 256})
        return dataset